included:
  - iOSApp
  - WatchApp
  - ComplicationApp
  - Shared

line_length:
  warning: 150
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

disabled_rules:
  - trailing_comma
  - todo
  - opening_brace

opt_in_rules:
  - empty_count
  - closure_spacing
  - first_where
  - modifier_order
  - force_unwrapping

type_name:
  excluded:
    - TennisCounter_Watch_AppApp

identifier_name:
  min_length:
    error: 1
  max_length:
    warning: 50
    error: 60
